### ISSUE TITLE
KeyError: '2963f9e8361b2b11bd01f8dbd610fb2e39dcffb1.jpg'

### ISSUE THREAD

**Issue by haijiecheng** [buptchan/scene-classification#1]
when I python train.py \
 --model_name=resnet50 \
 --optim=Adam \
 --learning_rate=1e-3 \
 --num_epochs=10
Build a Dataset: Image Enhance:False
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main()
  File "train.py", line 243, in main
    train_loss, train_acc_1, train_acc_3 = train_epoch(model, dataset, optimizer, logger=logger)
  File "train.py", line 34, in train_epoch
    dataloader = dataset.get_dataloader()
  File "/home/chenghj/scene-classification/dataset.py", line 154, in get_dataloader
    is_train=True)
  File "/home/chenghj/scene-classification/dataset.py", line 188, in __init__
    imgs = make_dataset(root, over_sample, class_to_idx, is_train)
  File "/home/chenghj/scene-classification/dataset.py", line 48, in make_dataset
    index = class_to_idx[target]
KeyError: '2963f9e8361b2b11bd01f8dbd610fb2e39dcffb1.jpg'
please tell me how to solve it.

**Comment by buptchan** [comment]
Obviously the problem is on the dataset. Just follow the error info and check whether this file "2963f9e8361b2b11bd01f8dbd610fb2e39dcffb1.jpg" in your dataset files.
